package services;

import model.Machine;
import model.Visitor;
import org.hibernate.Session;
import org.hibernate.Transaction;
import util.HibernateUtil;
import java.util.List;

public class LunaPark_Services {

    // No array repos now; we query DB using Hibernate sessions.

    public List<Machine> getAllMachines() {
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
            return session
                    .createQuery("from Machine", Machine.class)
                    .getResultList();
        }
    }

    public List<Visitor> getAllVisitors() {
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
            return session
                    .createQuery("from Visitor", Visitor.class)
                    .getResultList();
        }
    }

    /* ===================== CREATE ===================== */

    public String registerVisitor(Visitor visitor) {
        Transaction tx = null;

        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
            tx = session.beginTransaction();

            session.persist(visitor); // ID auto-generated by Hibernate

            tx.commit();
            return "Visitor registered successfully. ID = " + visitor.getId();

        } catch (Exception e) {
            if (tx != null) tx.rollback();
            return "Failed to register visitor: " + e.getMessage();
        }
    }
    public String registerMachine(Machine machine) {
        Transaction tx = null;

        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
            tx = session.beginTransaction();

            session.persist(machine); // ID auto-generated

            tx.commit();
            return "Machine registered successfully. ID = " + machine.getId();

        } catch (Exception e) {
            if (tx != null) tx.rollback();
            return "Failed to register machine: " + e.getMessage();
        }
    }
    public String topUpVisitor(Long visitorId, double amount) {
        if (amount <= 0) return "Amount must be greater than 0";

        Transaction tx = null;
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
            tx = session.beginTransaction();

            Visitor v = session.find(Visitor.class, visitorId);
            if (v == null) {
                tx.rollback();
                return "Visitor not found";
            }

            v.addBalance(amount);   // modifies managed entity
            // No explicit update needed; Hibernate dirty-checking will flush on commit.

            tx.commit();
            return "TopUp successful. new balance: " + v.getBalance();

        } catch (Exception e) {
            if (tx != null) tx.rollback();
            return "Error: " + e.getMessage();
        }
    }

    public String setMachineActive(Long machineId, boolean active) {
        Transaction tx = null;
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
            tx = session.beginTransaction();

            Machine m = session.find(Machine.class, machineId);
            if (m == null) {
                tx.rollback();
                return "Machine not found";
            }

            m.setActive(active);

            tx.commit();
            return "Machine Updated: " + m;

        } catch (Exception e) {
            if (tx != null) tx.rollback();
            return "Error: " + e.getMessage();
        }
    }

    public String BuyRide(Long visitorId, Long machineId) {
        Transaction tx = null;
        try (Session session = HibernateUtil.getSessionFactory().openSession()) {
            tx = session.beginTransaction();

            Visitor v = session.find(Visitor.class, visitorId);
            if (v == null) {
                tx.rollback();
                return "Visitor not found";
            }

            Machine m = session.find(Machine.class, machineId);
            if (m == null) {
                tx.rollback();
                return "Machine not found";
            }

            if (!m.isActive()) {
                tx.rollback();
                return "Machine is not active currently";
            }

            double price = m.getTicketPrice();

            // Your Visitor.charge throws IllegalArgumentException if insufficient
            v.charge(price);

            tx.commit();
            return "Ticket purchased. Visitor now rides '" + m.getName()
                    + "'. Remaining balance: " + v.getBalance();

        } catch (IllegalArgumentException e) {
            if (tx != null) tx.rollback();
            return "Insufficient balance or invalid amount. " + e.getMessage();
        } catch (Exception e) {
            if (tx != null) tx.rollback();
            return "Error: " + e.getMessage();
        }
    }
}
